### ISSUE TITLE
feedback on repos

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/airbnb-effect-of-price-on-reviews#76]
- all issues still relevant?
- file names all in lower caps
- makefiles incorrect: need file names as target, not a self-chosen name (unless it's your first rule)
- dependency structure incorrect (i.e., prerequisites need to be added)
- final rule (all) only needs to have the "final" data set to build, not all
- make needs to realize it's "done".
- clean legacy files - they are stored in your file version history anyways
- explicitly choose which files to keep (e.g., R vs. Rmd)
- output needs to be stored in `gen`, not in a subfolder of `src`. 
- remove legacy files

**Comment by RickMassuger** [comment]
barcharts to rmd file to write a short conclusion about the charts

**Comment by RickMassuger** [comment]
done
